/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Asus
 * Created: 18/12/2020
 */
create table comercios (
id_comercio number generated by default as identity,
nom_comercio varchar2(50) not null,
aforo_maximo number,
primary key(id_comercio)
);

create table servicios (
id_servicio number generated by default as identity,
id_comercio number not null,
nom_servicio varchar2(50) not null,
hora_apertura varchar2(10) not null,
hora_cierre varchar2(10) not null,
duracion number not null,
primary key(id_servicio),
foreign key (id_comercio) references comercios (id_comercio)
);

create table turnos (
id_turno number generated by default as identity,
id_servicio number not null,
fecha_turno date not null,
hora_inicio varchar2(10) not null,
hora_fin varchar2(10) not null,
estado varchar2(10) not null,
primary key(id_turno),
foreign key (id_servicio) references servicios (id_servicio)
);

create or replace 
PROCEDURE CREAR_TURNOS 
(
  P_ID_SERVICIO IN NUMBER  
, P_FECHA_INICIO IN VARCHAR2  
, P_FECHA_FIN IN VARCHAR2  
, CURSOR_ OUT sys_refcursor
) AS 
v_duracion NUMBER;
v_hora_apertura VARCHAR2(10);
v_hora_cierre VARCHAR2(10);
v_turnos_diarios number;
start_date NUMBER;
end_date NUMBER;
business_date DATE;
v_hora_apertura_turno VARCHAR2(10);
v_hora_cierre_turno VARCHAR2(10);
BEGIN
 
  -- Consultar informacion del servicio por id
  SELECT duracion, hora_apertura,  hora_cierre  into v_duracion, v_hora_apertura, v_hora_cierre  FROM servicios WHERE id_servicio = id_servicio;
   
  -- Calcular cuantos turnos se van a generar por dia
  SELECT ((24 * 60* (to_date(v_hora_cierre, 'hh24:mi') - to_date(v_hora_apertura, 'hh24:mi'))) / v_duracion) INTO v_turnos_diarios FROM dual;
  
  start_date := to_number(to_char(to_date(p_fecha_inicio, 'yyyy-MM-dd'), 'j'));
  end_date := to_number(to_char(to_date(p_FECHA_FIN, 'yyyy-MM-dd'), 'j'));
  
  -- Iterar sobre los dias
  FOR cur_r IN start_date..end_date LOOP
    
    business_date := to_date(cur_r, 'j');
    
    v_hora_apertura_turno := to_char(to_date(v_hora_apertura, 'hh24:mi') , 'hh24:mi');
    
   -- iterar sobre los turnos
   FOR turno in 1..v_turnos_diarios LOOP 
    v_hora_apertura_turno := to_char(to_date(v_hora_apertura_turno, 'hh24:mi') , 'hh24:mi');
    v_hora_cierre_turno := to_char(to_date(v_hora_apertura_turno, 'hh24:mi') +(1/1440*v_duracion) , 'hh24:mi');
     
     insert into turnos (id_servicio, fecha_turno, hora_inicio, hora_fin, estado ) values 
      (P_ID_SERVICIO,business_date,v_hora_apertura_turno,v_hora_cierre_turno,'1');
    
    -- Se incrementa la hora de acuerdo a la duracion del turno
    v_hora_apertura_turno := to_char(to_date(v_hora_apertura_turno, 'hh24:mi') +(1/1440*v_duracion) , 'hh24:mi');
    
   END LOOP;
    
  END LOOP;
  
  -- Se retorna los turnos creados
  OPEN CURSOR_ FOR
  SELECT t.id_turno, c.nom_comercio, s.nom_servicio, t.fecha_turno, t.hora_inicio, t.hora_fin  FROM comercios c
  JOIN servicios s ON c.id_comercio = s.id_comercio
  JOIN turnos t ON t.id_servicio = s.id_servicio
  WHERE s.id_servicio = P_ID_SERVICIO
  AND t.fecha_turno BETWEEN to_date(p_fecha_inicio, 'yyyy-MM-dd') AND to_date(p_fecha_fin, 'yyyy-MM-dd');
  
END CREAR_TURNOS;
